# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  inputs:
    script: 'ls -R'
    workingDirectory: '$(Build.SourcesDirectory)/apache-jmeter-5.1.1/bin'


- task: CmdLine@2
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)/apache-jmeter-5.1.1/bin'
    script: 'sh jmeter'
  
- task: CmdLine@2
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)/apache-jmeter-5.1.1/bin'
    script: 'sudo ./jmeter -n -t ''View Results Tree.jmx'' -l ''log.csv'' -e -o "JMeterTest"'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/JMeterTest-$(BuildID)'
    publishLocation: 'Container'
